# Module Output Artifacts Inspection

This notebook loads the final parquet artifacts from each module pipeline (the ones that get uploaded to HuggingFace) and displays their heads.

## Unified Schema

Each module produces three standardized parquet files:

1. **annotations.parquet**: `rsid, module, gene, phenotype, category`
2. **studies.parquet**: `rsid, module, pmid, population, p_value, conclusion, study_design`
3. **weights.parquet**: `rsid, genotype, module, weight, state, priority, conclusion, curator, method`
   - The uploaded weights file is joined with Ensembl data (includes chrom, start, end, ref, alts, clinvar, etc.)

In [2]:
from pathlib import Path
import polars as pl
from IPython.display import display

# Base output directory
MODULES_OUTPUT_DIR = Path("../data/output/modules")

# Available modules with their expected files
MODULES = [
    "longevitymap",
    "lipidmetabolism",
    "vo2max",
    "superhuman",
    "coronary",
    "drugs",
]

## Module Weights (Head Display)

For each module, shows row counts for annotations/studies and displays the **weights** head (the main file uploaded to HuggingFace).

In [3]:
for module in MODULES:
    module_dir = MODULES_OUTPUT_DIR / module
    
    if not module_dir.exists():
        print(f"⚠️  {module}: directory not found")
        continue
    
    # Annotations & Studies - just show row counts
    counts = []
    for file_type in ["annotations", "studies"]:
        path = module_dir / f"{file_type}.parquet"
        if path.exists():
            rows = pl.scan_parquet(path).select(pl.len()).collect().item()
            counts.append(f"{file_type}: {rows:,}")
    
    # Weights - show head
    weights_path = module_dir / f"{module}_ensembl_joined.parquet"
    if not weights_path.exists():
        weights_path = module_dir / "weights.parquet"
    
    if weights_path.exists():
        lf = pl.scan_parquet(weights_path)
        rows = lf.select(pl.len()).collect().item()
        print(f"\n{module.upper()} — {', '.join(counts)}, weights: {rows:,}")
        display(lf.head(5).collect())

LONGEVITYMAP — annotations: 520, studies: 3,460, weights: 1,386

shape: (5, 19)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ rsid       ┆ genotype   ┆ module     ┆ weight ┆ … ┆ pathogenic ┆ benign ┆ likely_pat ┆ likely_be │
│ ---        ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---    ┆ hogenic    ┆ nign      │
│ str        ┆ list[str]  ┆ str        ┆ f64    ┆   ┆ bool       ┆ bool   ┆ ---        ┆ ---       │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆ bool       ┆ bool      │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ rs922943   ┆ ["A", "C"] ┆ longevitym ┆ 0.07   ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ ap         ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs11086106 ┆ ["T", "T"] ┆ longevitym ┆ 0.14   ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ ap         ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs3120819  ┆ ["C", "T"] ┆ longevitym ┆ 0.24   ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ ap         ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs4964728  ┆ ["A", "T"] ┆ longevitym ┆ 0.105  ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ ap         ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs7301631  ┆ ["A", "C"] ┆ longevitym ┆ 0.105  ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ ap         ┆        ┆   ┆            ┆        ┆            ┆           │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

LIPIDMETABOLISM — annotations: 16, studies: 16, weights: 45

shape: (5, 19)
┌────────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬────────────┬───────────┐
│ rsid       ┆ genotype   ┆ module     ┆ weight ┆ … ┆ pathogenic ┆ benign ┆ likely_pat ┆ likely_be │
│ ---        ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---    ┆ hogenic    ┆ nign      │
│ str        ┆ list[str]  ┆ str        ┆ f64    ┆   ┆ bool       ┆ bool   ┆ ---        ┆ ---       │
│            ┆            ┆            ┆        ┆   ┆            ┆        ┆ bool       ┆ bool      │
╞════════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪════════════╪═══════════╡
│ rs6756629  ┆ ["A", "G"] ┆ lipidmetab ┆ -0.2   ┆ … ┆ false      ┆ true   ┆ false      ┆ true      │
│            ┆            ┆ olism      ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs6544713  ┆ ["C", "C"] ┆ lipidmetab ┆ 0.0    ┆ … ┆ false      ┆ true   ┆ false      ┆ false     │
│            ┆            ┆ olism      ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs12740374 ┆ ["G", "T"] ┆ lipidmetab ┆ -0.4   ┆ … ┆ false      ┆ false  ┆ false      ┆ false     │
│            ┆            ┆ olism      ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs268      ┆ ["A", "G"] ┆ lipidmetab ┆ -0.5   ┆ … ┆ false      ┆ true   ┆ false      ┆ true      │
│            ┆            ┆ olism      ┆        ┆   ┆            ┆        ┆            ┆           │
│ rs6544713  ┆ ["T", "T"] ┆ lipidmetab ┆ -0.8   ┆ … ┆ false      ┆ true   ┆ false      ┆ false     │
│            ┆            ┆ olism      ┆        ┆   ┆            ┆        ┆            ┆           │
└────────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴────────────┴───────────┘

VO2MAX — annotations: 13, studies: 13, weights: 39

shape: (5, 19)
┌────────────┬────────────┬────────┬────────┬───┬────────────┬────────┬──────────────┬─────────────┐
│ rsid       ┆ genotype   ┆ module ┆ weight ┆ … ┆ pathogenic ┆ benign ┆ likely_patho ┆ likely_beni │
│ ---        ┆ ---        ┆ ---    ┆ ---    ┆   ┆ ---        ┆ ---    ┆ genic        ┆ gn          │
│ str        ┆ list[str]  ┆ str    ┆ f64    ┆   ┆ bool       ┆ bool   ┆ ---          ┆ ---         │
│            ┆            ┆        ┆        ┆   ┆            ┆        ┆ bool         ┆ bool        │
╞════════════╪════════════╪════════╪════════╪═══╪════════════╪════════╪══════════════╪═════════════╡
│ rs4952535  ┆ ["G", "G"] ┆ vo2max ┆ 0.5    ┆ … ┆ false      ┆ false  ┆ false        ┆ false       │
│ rs1695     ┆ ["A", "G"] ┆ vo2max ┆ 0.5    ┆ … ┆ false      ┆ true   ┆ false        ┆ false       │
│ rs10921078 ┆ ["A", "G"] ┆ vo2max ┆ 0.0    ┆ … ┆ false      ┆ false  ┆ false        ┆ false       │
│ rs884736   ┆ ["A", "A"] ┆ vo2max ┆ -1.0   ┆ … ┆ false      ┆ false  ┆ false        ┆ false       │
│ rs4952535  ┆ ["A", "A"] ┆ vo2max ┆ 0.0    ┆ … ┆ false      ┆ false  ┆ false        ┆ false       │
└────────────┴────────────┴────────┴────────┴───┴────────────┴────────┴──────────────┴─────────────┘

SUPERHUMAN — annotations: 847, studies: 850, weights: 2

shape: (2, 19)
┌────────┬────────────┬────────────┬────────┬───┬────────────┬────────┬──────────────┬─────────────┐
│ rsid   ┆ genotype   ┆ module     ┆ weight ┆ … ┆ pathogenic ┆ benign ┆ likely_patho ┆ likely_beni │
│ ---    ┆ ---        ┆ ---        ┆ ---    ┆   ┆ ---        ┆ ---    ┆ genic        ┆ gn          │
│ str    ┆ list[str]  ┆ str        ┆ f64    ┆   ┆ bool       ┆ bool   ┆ ---          ┆ ---         │
│        ┆            ┆            ┆        ┆   ┆            ┆        ┆ bool         ┆ bool        │
╞════════╪════════════╪════════════╪════════╪═══╪════════════╪════════╪══════════════╪═════════════╡
│ rs7412 ┆ ["T", "T"] ┆ superhuman ┆ null   ┆ … ┆ true       ┆ true   ┆ false        ┆ true        │
│ rs5082 ┆ ["C", "C"] ┆ superhuman ┆ null   ┆ … ┆ true       ┆ false  ┆ false        ┆ false       │
└────────┴────────────┴────────────┴────────┴───┴────────────┴────────┴──────────────┴─────────────┘

CORONARY — annotations: 27, studies: 79, weights: 81

shape: (5, 19)
┌────────────┬────────────┬──────────┬────────┬───┬────────────┬────────┬─────────────┬────────────┐
│ rsid       ┆ genotype   ┆ module   ┆ weight ┆ … ┆ pathogenic ┆ benign ┆ likely_path ┆ likely_ben │
│ ---        ┆ ---        ┆ ---      ┆ ---    ┆   ┆ ---        ┆ ---    ┆ ogenic      ┆ ign        │
│ str        ┆ list[str]  ┆ str      ┆ f64    ┆   ┆ bool       ┆ bool   ┆ ---         ┆ ---        │
│            ┆            ┆          ┆        ┆   ┆            ┆        ┆ bool        ┆ bool       │
╞════════════╪════════════╪══════════╪════════╪═══╪════════════╪════════╪═════════════╪════════════╡
│ rs11206510 ┆ ["T", "T"] ┆ coronary ┆ 0.0    ┆ … ┆ false      ┆ false  ┆ false       ┆ false      │
│ rs3184504  ┆ ["C", "C"] ┆ coronary ┆ 0.0    ┆ … ┆ false      ┆ true   ┆ false       ┆ false      │
│ rs3184504  ┆ ["T", "T"] ┆ coronary ┆ -0.7   ┆ … ┆ false      ┆ true   ┆ false       ┆ false      │
│ rs7250581  ┆ ["A", "A"] ┆ coronary ┆ 0.0    ┆ … ┆ false      ┆ false  ┆ false       ┆ false      │
│ rs8055236  ┆ ["T", "T"] ┆ coronary ┆ 0.0    ┆ … ┆ false      ┆ false  ┆ false       ┆ false      │
└────────────┴────────────┴──────────┴────────┴───┴────────────┴────────┴─────────────┴────────────┘

DRUGS — annotations: 740, studies: 854, weights: 854

shape: (5, 9)
┌───────────┬──────────┬────────┬────────┬───┬──────────┬───────────────┬──────────┬───────────────┐
│ rsid      ┆ genotype ┆ module ┆ weight ┆ … ┆ priority ┆ conclusion    ┆ curator  ┆ method        │
│ ---       ┆ ---      ┆ ---    ┆ ---    ┆   ┆ ---      ┆ ---           ┆ ---      ┆ ---           │
│ str       ┆ str      ┆ str    ┆ f64    ┆   ┆ str      ┆ str           ┆ str      ┆ str           │
╞═══════════╪══════════╪════════╪════════╪═══╪══════════╪═══════════════╪══════════╪═══════════════╡
│ rs6822844 ┆ ??       ┆ drugs  ┆ null   ┆ … ┆ null     ┆ rituximab:    ┆ PharmGKB ┆ pharmacogenom │
│           ┆          ┆        ┆        ┆   ┆          ┆ Genotype GG   ┆          ┆ ics_db        │
│           ┆          ┆        ┆        ┆   ┆          ┆ is asso…      ┆          ┆               │
│ rs2314339 ┆ ??       ┆ drugs  ┆ null   ┆ … ┆ null     ┆ lithium:      ┆ PharmGKB ┆ pharmacogenom │
│           ┆          ┆        ┆        ┆   ┆          ┆ Allele T is   ┆          ┆ ics_db        │
│           ┆          ┆        ┆        ┆   ┆          ┆ associate…    ┆          ┆               │
│ rs20455   ┆ ??       ┆ drugs  ┆ null   ┆ … ┆ null     ┆ pravastatin:  ┆ PharmGKB ┆ pharmacogenom │
│           ┆          ┆        ┆        ┆   ┆          ┆ Genotypes AG  ┆          ┆ ics_db        │
│           ┆          ┆        ┆        ┆   ┆          ┆ + GG…         ┆          ┆               │
│ rs683369  ┆ ??       ┆ drugs  ┆ null   ┆ … ┆ null     ┆ imatinib:     ┆ PharmGKB ┆ pharmacogenom │
│           ┆          ┆        ┆        ┆   ┆          ┆ Genotypes CG  ┆          ┆ ics_db        │
│           ┆          ┆        ┆        ┆   ┆          ┆ + GG is…      ┆          ┆               │
│ rs1883112 ┆ ??       ┆ drugs  ┆ null   ┆ … ┆ null     ┆ idarubicin:   ┆ PharmGKB ┆ pharmacogenom │
│           ┆          ┆        ┆        ┆   ┆          ┆ Genotype AA   ┆          ┆ ics_db        │
│           ┆          ┆        ┆        ┆   ┆          ┆ is ass…       ┆          ┆               │
└───────────┴──────────┴────────┴────────┴───┴──────────┴───────────────┴──────────┴───────────────┘

## Summary Table

Overview of all module output files with row counts and sizes.

In [4]:
summary_rows = []

for module in MODULES:
    module_dir = MODULES_OUTPUT_DIR / module
    
    if not module_dir.exists():
        continue
    
    for parquet_file in sorted(module_dir.glob("*.parquet")):
        lf = pl.scan_parquet(parquet_file)
        row_count = lf.select(pl.len()).collect().item()
        col_count = len(lf.collect_schema())
        size_mb = parquet_file.stat().st_size / (1024 * 1024)
        
        summary_rows.append({
            "module": module,
            "file": parquet_file.name,
            "rows": row_count,
            "columns": col_count,
            "size_mb": round(size_mb, 3),
        })

summary_df = pl.DataFrame(summary_rows)
print("\n📊 Summary of All Module Output Files:")
display(summary_df)

📊 Summary of All Module Output Files:

shape: (23, 5)
┌─────────────────┬─────────────────────────────────┬──────┬─────────┬─────────┐
│ module          ┆ file                            ┆ rows ┆ columns ┆ size_mb │
│ ---             ┆ ---                             ┆ ---  ┆ ---     ┆ ---     │
│ str             ┆ str                             ┆ i64  ┆ i64     ┆ f64     │
╞═════════════════╪═════════════════════════════════╪══════╪═════════╪═════════╡
│ longevitymap    ┆ annotations.parquet             ┆ 520  ┆ 5       ┆ 0.006   │
│ longevitymap    ┆ longevitymap_ensembl_joined.pa… ┆ 1386 ┆ 19      ┆ 0.028   │
│ longevitymap    ┆ studies.parquet                 ┆ 3460 ┆ 7       ┆ 0.079   │
│ longevitymap    ┆ weights.parquet                 ┆ 1386 ┆ 9       ┆ 0.02    │
│ lipidmetabolism ┆ annotations.parquet             ┆ 16   ┆ 5       ┆ 0.002   │
│ …               ┆ …                               ┆ …    ┆ …       ┆ …       │
│ coronary        ┆ studies.parquet                 ┆ 79   ┆ 7       ┆ 0.014   │
│ coronary        ┆ weights.parquet                 ┆ 81   ┆ 9       ┆ 0.01    │
│ drugs           ┆ annotations.parquet             ┆ 740  ┆ 5       ┆ 0.006   │
│ drugs           ┆ studies.parquet                 ┆ 854  ┆ 7       ┆ 0.019   │
│ drugs           ┆ weights.parquet                 ┆ 854  ┆ 9       ┆ 0.02    │
└─────────────────┴─────────────────────────────────┴──────┴─────────┴─────────┘

## Files That Get Uploaded to HuggingFace

The following files are uploaded to `just-dna-seq/annotators` repository:

| Module | HuggingFace Path | Local Source |
|--------|------------------|-------------|
| longevitymap | `data/longevitymap/annotations.parquet` | `annotations.parquet` |
| longevitymap | `data/longevitymap/studies.parquet` | `studies.parquet` |
| longevitymap | `data/longevitymap/weights.parquet` | `longevitymap_ensembl_joined.parquet` |
| ... | ... | ... |

In [5]:
# List what would be uploaded for each module
upload_manifest = []

for module in MODULES:
    module_dir = MODULES_OUTPUT_DIR / module
    
    if not module_dir.exists():
        continue
    
    annotations_path = module_dir / "annotations.parquet"
    studies_path = module_dir / "studies.parquet"
    ensembl_joined_path = module_dir / f"{module}_ensembl_joined.parquet"
    weights_path = module_dir / "weights.parquet"
    
    # Determine weights source
    weights_source = ensembl_joined_path if ensembl_joined_path.exists() else weights_path
    
    for local_path, hf_name in [
        (annotations_path, "annotations.parquet"),
        (studies_path, "studies.parquet"),
        (weights_source, "weights.parquet"),
    ]:
        if local_path.exists():
            size_mb = local_path.stat().st_size / (1024 * 1024)
            row_count = pl.scan_parquet(local_path).select(pl.len()).collect().item()
            
            upload_manifest.append({
                "module": module,
                "hf_path": f"data/{module}/{hf_name}",
                "local_file": local_path.name,
                "rows": row_count,
                "size_mb": round(size_mb, 3),
            })

upload_df = pl.DataFrame(upload_manifest)
print("\n🚀 Files Ready for HuggingFace Upload:")
display(upload_df)

total_size = upload_df["size_mb"].sum()
total_rows = upload_df["rows"].sum()
print(f"\n📦 Total: {len(upload_manifest)} files, {total_rows:,} rows, {total_size:.2f} MB")

🚀 Files Ready for HuggingFace Upload:

shape: (18, 5)
┌─────────────────┬───────────────────────────────┬───────────────────────────────┬──────┬─────────┐
│ module          ┆ hf_path                       ┆ local_file                    ┆ rows ┆ size_mb │
│ ---             ┆ ---                           ┆ ---                           ┆ ---  ┆ ---     │
│ str             ┆ str                           ┆ str                           ┆ i64  ┆ f64     │
╞═════════════════╪═══════════════════════════════╪═══════════════════════════════╪══════╪═════════╡
│ longevitymap    ┆ data/longevitymap/annotations ┆ annotations.parquet           ┆ 520  ┆ 0.006   │
│                 ┆ .…                            ┆                               ┆      ┆         │
│ longevitymap    ┆ data/longevitymap/studies.par ┆ studies.parquet               ┆ 3460 ┆ 0.079   │
│                 ┆ q…                            ┆                               ┆      ┆         │
│ longevitymap    ┆ data/longevitymap/weights.par ┆ longevitymap_ensembl_joined.p ┆ 1386 ┆ 0.028   │
│                 ┆ q…                            ┆ a…                            ┆      ┆         │
│ lipidmetabolism ┆ data/lipidmetabolism/annotati ┆ annotations.parquet           ┆ 16   ┆ 0.002   │
│                 ┆ o…                            ┆                               ┆      ┆         │
│ lipidmetabolism ┆ data/lipidmetabolism/studies. ┆ studies.parquet               ┆ 16   ┆ 0.009   │
│                 ┆ p…                            ┆                               ┆      ┆         │
│ …               ┆ …                             ┆ …                             ┆ …    ┆ …       │
│ coronary        ┆ data/coronary/studies.parquet ┆ studies.parquet               ┆ 79   ┆ 0.014   │
│ coronary        ┆ data/coronary/weights.parquet ┆ coronary_ensembl_joined.parqu ┆ 81   ┆ 0.009   │
│                 ┆                               ┆ e…                            ┆      ┆         │
│ drugs           ┆ data/drugs/annotations.parque ┆ annotations.parquet           ┆ 740  ┆ 0.006   │
│                 ┆ t                             ┆                               ┆      ┆         │
│ drugs           ┆ data/drugs/studies.parquet    ┆ studies.parquet               ┆ 854  ┆ 0.019   │
│ drugs           ┆ data/drugs/weights.parquet    ┆ weights.parquet               ┆ 854  ┆ 0.02    │
└─────────────────┴───────────────────────────────┴───────────────────────────────┴──────┴─────────┘

📦 Total: 18 files, 9,842 rows, 0.24 MB