# Modules update
## Notebook to update current just-dna-seq modules

In [5]:
import polars as pl
import polars_bio as pb
import sqlite3
from pathlib import Path
from pycomfort import files

from platformdirs import user_cache_dir

# Configure Polars to show more rows and columns
pl.Config.set_tbl_rows(-1)  # Show all rows
pl.Config.set_tbl_cols(-1)  # Show all columns
pl.Config.set_tbl_width_chars(1000)  # Increase table width
pl.Config.set_fmt_str_lengths(1000)  # Show longer string values without truncation

polars.config.Config

In [6]:
from os import listdir
from prepare_annotations.resource import get_cache_dir
cache = get_cache_dir()
ensembl_cache = cache / "ensembl" / "homo_sapiens" 
listdir(ensembl_cache)

['homo_sapiens-chr2.parquet',
 'homo_sapiens-chr9.parquet',
 'homo_sapiens-chr17.parquet',
 'homo_sapiens-chr21.parquet',
 'homo_sapiens-chrY.parquet',
 'homo_sapiens-chr20.parquet',
 'homo_sapiens-chr19.parquet',
 'homo_sapiens-chr4.parquet',
 'homo_sapiens-chr14.parquet',
 'homo_sapiens-chr3.parquet',
 'homo_sapiens-chr13.parquet',
 'homo_sapiens-chrX.parquet',
 'homo_sapiens-chr6.parquet',
 'homo_sapiens-chr5.parquet',
 'homo_sapiens-chr22.parquet',
 'homo_sapiens-chr1.parquet',
 'homo_sapiens-chrMT.parquet',
 'vcf',
 'homo_sapiens-chr15.parquet',
 'homo_sapiens-chr16.tmp.parquet',
 'homo_sapiens-chr7.parquet',
 'homo_sapiens-chr12.parquet',
 'homo_sapiens-chr18.parquet',
 'homo_sapiens-chr8.tmp.parquet',
 'homo_sapiens-chr11.parquet',
 'homo_sapiens-chr10.parquet']

### Testing the parquets

In [7]:
chr1 = pl.scan_parquet(ensembl_cache / "homo_sapiens-chr1.parquet")
chr1.head(5).collect()

shape: (5, 41)
┌───────┬───────┬───────┬──────────────┬─────┬───────┬─────────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬──────┬──────┬──────┬──────┐
│ chrom ┆ start ┆ end   ┆ id           ┆ ref ┆ alt   ┆ alts            ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA   ┆ MAF  ┆ MAC  ┆ AA   │
│ ---   ┆ ---   ┆ ---   ┆ ---          ┆ --- ┆ ---   ┆ ---             ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str          ┆ str ┆ str   ┆ list[str]       ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str  ┆ f32  ┆ i32  ┆ str  │
╞═══════╪═══════╪═══════╪══════════════╪═════╪═══════╪═════════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪══════╪══════╪══════╪══════╡
│ 1     ┆ 10001 ┆ 10001 ┆ rs1570391677 ┆ T   ┆ A|C   ┆ ["A", "C"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10002 ┆ 10002 ┆ rs1570391692 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10003 ┆ 10003 ┆ rs1570391694 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10007 ┆ 10007 ┆ rs1639538116 ┆ T   ┆ C|G   ┆ ["C", "G"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10008 ┆ 10008 ┆ rs1570391698 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
└───────┴───────┴───────┴──────────────┴─────┴───────┴─────────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴──────┴──────┴──────┴──────┘

In [8]:
chr1_updated = chr1.with_columns(alts=pl.col("alt").str.split("|")).select(pl.col(chr1.collect_schema().names()[:chr1.collect_schema().names().index("alt")+1] + ["alts"] + chr1.collect_schema().names()[chr1.collect_schema().names().index("alt")+1:]))
chr1_updated.head(5).collect()

shape: (5, 41)
┌───────┬───────┬───────┬──────────────┬─────┬───────┬─────────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬──────┬──────┬──────┬──────┐
│ chrom ┆ start ┆ end   ┆ id           ┆ ref ┆ alt   ┆ alts            ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA   ┆ MAF  ┆ MAC  ┆ AA   │
│ ---   ┆ ---   ┆ ---   ┆ ---          ┆ --- ┆ ---   ┆ ---             ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str          ┆ str ┆ str   ┆ list[str]       ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str  ┆ f32  ┆ i32  ┆ str  │
╞═══════╪═══════╪═══════╪══════════════╪═════╪═══════╪═════════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪══════╪══════╪══════╪══════╡
│ 1     ┆ 10001 ┆ 10001 ┆ rs1570391677 ┆ T   ┆ A|C   ┆ ["A", "C"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10002 ┆ 10002 ┆ rs1570391692 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10003 ┆ 10003 ┆ rs1570391694 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10007 ┆ 10007 ┆ rs1639538116 ┆ T   ┆ C|G   ┆ ["C", "G"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10008 ┆ 10008 ┆ rs1570391698 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
└───────┴───────┴───────┴──────────────┴─────┴───────┴─────────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴──────┴──────┴──────┴──────┘

In [11]:

chr1_updated.filter(pl.col("TSA")=="SNV").filter(pl.col("alts").list.len() > 2).head(5).collect()

shape: (5, 41)
┌───────┬───────┬───────┬──────────────┬─────┬───────┬─────────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬──────┬──────┬──────┬──────┐
│ chrom ┆ start ┆ end   ┆ id           ┆ ref ┆ alt   ┆ alts            ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA   ┆ MAF  ┆ MAC  ┆ AA   │
│ ---   ┆ ---   ┆ ---   ┆ ---          ┆ --- ┆ ---   ┆ ---             ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str          ┆ str ┆ str   ┆ list[str]       ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str  ┆ f32  ┆ i32  ┆ str  │
╞═══════╪═══════╪═══════╪══════════════╪═════╪═══════╪═════════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪══════╪══════╪══════╪══════╡
│ 1     ┆ 10008 ┆ 10008 ┆ rs1570391698 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10014 ┆ 10014 ┆ rs1639538207 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10015 ┆ 10015 ┆ rs1570391706 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10020 ┆ 10020 ┆ rs1570391708 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10027 ┆ 10027 ┆ rs1570391716 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
└───────┴───────┴───────┴──────────────┴─────┴───────┴─────────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴──────┴──────┴──────┴──────┘

## Loading modules

In [12]:
from pycomfort import files
from pathlib import Path
base = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data = base / "data"
modules = data / "modules"
files.tprint(modules)

modules
	just_drugs
		annotation_tab.tsv
	just_longevitymap
		longevitymap.sqlite
	just_coronary
		coronary.sqlite
	just_lipidmetabolism
		lipid_metabolism.sqlite
	just_vo2max
		vo2max.sqlite
	just_superhuman
		superhuman.sqlite
	just_prs
		prs.sqlite
	just_cancer
		genes.txt

## Modules

In [13]:
import sqlite3
import polars as pl

# Connect to the database
db_path = modules / "just_longevitymap" / "longevitymap.sqlite"
conn = sqlite3.connect(db_path)

# Get list of all tables in the database
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in the database:")
for table in tables:
    print(f"  - {table[0]}")

Tables in the database:
  - gene
  - population
  - variant
  - allele_weights
  - categories

In [14]:
# Get schema for each table
for table in tables:
    table_name = table[0]
    print(f"\nSchema for table '{table_name}':")
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    for col in columns:
        print(f"  {col[1]} ({col[2]})")

Schema for table 'gene':
  id (INTEGER)
  name (TEXT)
  symbol (TEXT)
  alias (TEXT)
  description (TEXT)
  omim (TEXT)
  ensembl (TEXT)
  uniprot (TEXT)
  unigene (TEXT)
  cytogenetic_location (TEXT)

Schema for table 'population':
  id (INTEGER)
  name (TEXT)

Schema for table 'variant':
  id (INTEGER)
  location (TEXT)
  study_design (TEXT)
  conclusions (TEXT)
  association (TEXT)
  gender (TEXT)
  quickref (TEXT)
  quickyear (INTEGER)
  quickpubmed (TEXT)
  identifier (TEXT)
  gene_id (INTEGER)
  population_id (INTEGER)

Schema for table 'allele_weights':
  id (INTEGER)
  allele (TEXT)
  state (TEXT)
  zygosity (TEXT)
  weight (REAL)
  rsid (TEXT)
  priority (TEXT)
  category_id (INTEGER)

Schema for table 'categories':
  id (INTEGER)
  name (TEXT)

## Join with rsid

In [89]:
from prepare_annotations.resource import get_cache_dir
from pycomfort import files
cache = get_cache_dir()
ensembl_cache = cache / "ensembl_variations" / "splitted_variants"
files.tprint(ensembl_cache)

splitted_variants
	ensembl_variations.duckdb
	sequence_alteration
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrX.parquet
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chr15.parquet
		homo_sapiens-chr16.parquet
		homo_sapiens-chr7.parquet
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet
	SNV
		homo_sapiens-chr5.vortex
		homo_sapiens-chr2.vortex
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr16.vortex
		homo_sapiens-chr19.vortex
		homo_sapiens-chr10.vortex
		homo_sapiens-chr14.vortex
		homo_sapiens-chr21.vortex
		homo_sapiens-chr4.vortex
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr1.vortex
		homo_sapiens-chr17.vortex
		homo_sapiens-chrY.vortex
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr7.vortex
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrMT.vortex
		homo_sapiens-chrX.parquet
		homo_sapiens-chr22.vortex
		homo_sapiens-chr11.vortex
		homo_sapiens-chr3.vortex
		homo_sapiens-chrX.vortex
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chr18.vortex
		homo_sapiens-chrMT.parquet
		homo_sapiens-chr9.vortex
		homo_sapiens-chr13.vortex
		homo_sapiens-chr8.vortex
		homo_sapiens-chr15.parquet
		homo_sapiens-chr15.vortex
		homo_sapiens-chr16.parquet
		homo_sapiens-chr12.vortex
		homo_sapiens-chr7.parquet
		homo_sapiens-chr6.vortex
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr20.vortex
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet
	deletion
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrX.parquet
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chrMT.parquet
		homo_sapiens-chr15.parquet
		homo_sapiens-chr16.parquet
		homo_sapiens-chr7.parquet
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet
	.cache
		huggingface
			.gitignore
			download
				data
					SNV
						homo_sapiens-chr10.parquet.lock
						7Er4KGaQ864TcwVpTZZyKlzCRg8=.7fb6bab42eefdc6bcafea209e3e714e26f231a26b31ce87fb5000e62e88744d4.incomplete
						homo_sapiens-chr3.parquet.lock
						l9JyYbbIJaTa9Gn8d7gvkW02bQ8=.81e68a61969c5219cca06c9fde8484ee3c8c352946eec692141aed54e30a8e7d.incomplete
						homo_sapiens-chr20.parquet.lock
						d9XG1rmj6BlrpGCV8ykxOheutQ4=.4f2f10904875ef090221ca6e7250bc11b1a983bf1f1c0d4aff4484f3ef9169a4.incomplete
						9RdFa-rh6cKJ0cyHZP6bqakCRi8=.0f66e4c66904d74f0faa8e0680ef19af2d1720d796d9050d1b002df830a05c66.incomplete
						PH8vzetuICyrztErea0l8LgNLu0=.36b469844a2886636ca2ef8bf162e0dd24a603b1d60cb430c7b632743ae5d790.incomplete
						homo_sapiens-chr21.parquet.lock
						2O_O5GoaNm-DeaBPgoDJAPi4Xm8=.8fdf8afb9807f5c48c3736d979d3cfc571c2154a70b838c0070d94a168666350.incomplete
						b96ZLEdwdYeGxuCc57UPnCHLffE=.da18a8495575b41e9b28424eaa05e9b91c67817756172709370a7b58b569d0ff.incomplete
						homo_sapiens-chr11.parquet.lock
						homo_sapiens-chr17.parquet.lock
						homo_sapiens-chr16.parquet.lock
						ahSVL5eAWYOzSrf6xU-ifgrBeYQ=.623d1e3e6d821178f7bbd56b3965552ccc3dfebcd2afa557ba146f735f70867e.incomplete
						homo_sapiens-chr13.parquet.lock
						P5ouzMc1sgZkoAyGg3762Kp5lwo=.05d210177799d12e60c151b35283b8110c27d31395a85e1d95b35e47f5412a81.incomplete
						homo_sapiens-chr2.parquet.lock
						n52A3dKAkZws8kgXLiXMKIO6PYg=.e4294f85063cd79a101c40e3e2ed7e4381328ebda10dd1c8a427a80619100cc5.incomplete
						homo_sapiens-chr14.parquet.lock
						homo_sapiens-chr18.parquet.lock
						wAYHtEYCutL3Kk1ZFvx4dBLohBo=.0ab543c110ecbb31f620f37b747939d464693d9a215f73702479384f9ce8d460.incomplete
						OAqMvA89DNiSu95C2uNpWrdrH0M=.a953627aa38bfc72ee71594451c4dc47b38941d4f41bb237f26c622f32d7c769.incomplete
						Mgafno5aUQpISiYE_IptOVWRRcA=.46ffa5c91f7697e46e5694252e0bd0355e9f3c9820944f9596dc0282828eb18a.incomplete
						jLTaA-j2-Qwll8jy1VJ_LD6g_Ok=.e6dd16b7313d9ae78e1700b848658a33e9ebc00028b64ea4637bea16fd5ae8bc.incomplete
						homo_sapiens-chr19.parquet.lock
						jtqzuxz0LFg67RJmPKx5ycAjJQ0=.aa474e8ca5cc3bcd51633e13b1718541d1e84f5d195256b010293c94a8b6fc3e.incomplete
						homo_sapiens-chr12.parquet.lock
						homo_sapiens-chr22.parquet.lock
						homo_sapiens-chr15.parquet.lock
						homo_sapiens-chr1.parquet.lock
						_TiBXodUlBeVx-XXQz0MV_aIBzY=.30a9a3bbcb3bade666709593f31af5656e7791c436590c9f1dae1f1125e9fe73.incomplete
	indel
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrX.parquet
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chrMT.parquet
		homo_sapiens-chr15.parquet
		homo_sapiens-chr16.parquet
		homo_sapiens-chr7.parquet
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet
	insertion
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrX.parquet
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chrMT.parquet
		homo_sapiens-chr15.parquet
		homo_sapiens-chr16.parquet
		homo_sapiens-chr7.parquet
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet
	data
		SNV
	substitution
		homo_sapiens-chr2.parquet
		homo_sapiens-chr9.parquet
		homo_sapiens-chr17.parquet
		homo_sapiens-chr21.parquet
		homo_sapiens-chr8.parquet
		homo_sapiens-chrY.parquet
		homo_sapiens-chr20.parquet
		homo_sapiens-chr19.parquet
		homo_sapiens-chr4.parquet
		homo_sapiens-chr14.parquet
		homo_sapiens-chr3.parquet
		homo_sapiens-chr13.parquet
		homo_sapiens-chrX.parquet
		homo_sapiens-chr6.parquet
		homo_sapiens-chr5.parquet
		homo_sapiens-chr22.parquet
		homo_sapiens-chr1.parquet
		homo_sapiens-chrMT.parquet
		homo_sapiens-chr15.parquet
		homo_sapiens-chr16.parquet
		homo_sapiens-chr7.parquet
		homo_sapiens-chr12.parquet
		homo_sapiens-chr18.parquet
		homo_sapiens-chr11.parquet
		homo_sapiens-chr10.parquet

In [7]:
weights = pl.read_database("SELECT id, allele, state, zygosity, weight, rsid, priority, category_id FROM allele_weights", connection=conn)
weights.head(5)

shape: (5, 8)
┌─────┬────────┬───────┬──────────┬────────┬──────────┬──────────┬─────────────┐
│ id  ┆ allele ┆ state ┆ zygosity ┆ weight ┆ rsid     ┆ priority ┆ category_id │
│ --- ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---      ┆ ---      ┆ ---         │
│ i64 ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str      ┆ str      ┆ i64         │
╞═════╪════════╪═══════╪══════════╪════════╪══════════╪══════════╪═════════════╡
│ 0   ┆ T      ┆ alt   ┆ het      ┆ 0.5    ┆ rs7412   ┆ 1.0      ┆ 1           │
│ 1   ┆ T      ┆ alt   ┆ hom      ┆ 1.0    ┆ rs7412   ┆ 1.0      ┆ 1           │
│ 2   ┆ C      ┆ alt   ┆ het      ┆ -0.5   ┆ rs429358 ┆ 1.0      ┆ 1           │
│ 3   ┆ C      ┆ alt   ┆ hom      ┆ -1.0   ┆ rs429358 ┆ 1.0      ┆ 1           │
│ 4   ┆ G      ┆ ref   ┆ hom      ┆ 0.97   ┆ rs5882   ┆ 0.97     ┆ 1           │
└─────┴────────┴───────┴──────────┴────────┴──────────┴──────────┴─────────────┘

In [8]:
# Get unique rsids from small weights table
rsids = weights["rsid"].unique().to_list()
print(f"Filtering for {len(rsids)} unique rsids")

Filtering for 528 unique rsids

In [9]:
# Filter the large lazy frame first, then join
joined = df_ensembl.select(
    pl.col("chrom"), 
    pl.col("start"), 
    pl.col("end")
    ).filter(
    pl.col("id").is_in(rsids)
).join(
    weights.lazy(),
    left_on="id",
    right_on="rsid",
    how="inner"
)

In [10]:
example = joined.head(5).collect(engine="streaming")
example

ColumnNotFoundError: unable to find column "id"; valid columns: ["chrom", "start", "end"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
SELECT [col("chrom"), col("start"), col("end")]
  Parquet SCAN [/home/antonkulaga/.cache/just_dna_pipelines/ensembl_variations/splitted_variants/SNV/homo_sapiens-chr1.parquet, ... 24 other sources] [id: 129231707533808]
  PROJECT */40 COLUMNS

In [26]:
result = joined.collect(engine="streaming")
result

shape: (1_788, 47)
┌───────┬──────────┬──────────┬────────────┬───┬──────────┬────────┬──────────┬─────────────┐
│ chrom ┆ start    ┆ end      ┆ id         ┆ … ┆ zygosity ┆ weight ┆ priority ┆ category_id │
│ ---   ┆ ---      ┆ ---      ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ---      ┆ ---         │
│ str   ┆ u32      ┆ u32      ┆ str        ┆   ┆ str      ┆ f64    ┆ str      ┆ i64         │
╞═══════╪══════════╪══════════╪════════════╪═══╪══════════╪════════╪══════════╪═════════════╡
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 19    ┆ 44919689 ┆ 44919689 ┆ rs4420638  ┆ … ┆ het      ┆ -0.375 ┆ 0.75     ┆ 1           │
│ …     ┆ …        ┆ …        ┆ …          ┆ … ┆ …        ┆ …      ┆ …        ┆ …           │
│ 12    ┆ 57774005 ┆ 57774005 ┆ rs10877015 ┆ … ┆ hom      ┆ 0.12   ┆ 0.12     ┆ 11          │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ het      ┆ 0.065  ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ het      ┆ 0.065  ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ hom      ┆ 0.13   ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ hom      ┆ 0.13   ┆ 0.13     ┆ 0           │
└───────┴──────────┴──────────┴────────────┴───┴──────────┴────────┴──────────┴─────────────┘

In [33]:
weights.filter(pl.col("rsid") == "rs7896005")

shape: (2, 8)
┌─────┬────────┬───────┬──────────┬────────┬───────────┬──────────┬─────────────┐
│ id  ┆ allele ┆ state ┆ zygosity ┆ weight ┆ rsid      ┆ priority ┆ category_id │
│ --- ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---       ┆ ---      ┆ ---         │
│ i64 ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str       ┆ str      ┆ i64         │
╞═════╪════════╪═══════╪══════════╪════════╪═══════════╪══════════╪═════════════╡
│ 39  ┆ G      ┆ alt   ┆ het      ┆ 0.36   ┆ rs7896005 ┆ 0.72     ┆ 5           │
│ 40  ┆ G      ┆ alt   ┆ hom      ┆ 0.72   ┆ rs7896005 ┆ 0.72     ┆ 5           │
└─────┴────────┴───────┴──────────┴────────┴───────────┴──────────┴─────────────┘

In [31]:
result.filter(pl.col("id") == "rs7896005")

shape: (4, 47)
┌───────┬──────────┬──────────┬───────────┬───┬──────────┬────────┬──────────┬─────────────┐
│ chrom ┆ start    ┆ end      ┆ id        ┆ … ┆ zygosity ┆ weight ┆ priority ┆ category_id │
│ ---   ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---    ┆ ---      ┆ ---         │
│ str   ┆ u32      ┆ u32      ┆ str       ┆   ┆ str      ┆ f64    ┆ str      ┆ i64         │
╞═══════╪══════════╪══════════╪═══════════╪═══╪══════════╪════════╪══════════╪═════════════╡
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
└───────┴──────────┴──────────┴───────────┴───┴──────────┴────────┴──────────┴─────────────┘

In [15]:
weights.shape

(1043, 8)

In [ ]:
# Check all tables for columns containing 'rsid' or 'rs' in the name
for table in tables:
    table_name = table[0]
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    rsid_columns = [col[1] for col in columns if 'rs' in col[1].lower() or 'id' in col[1].lower()]
    if rsid_columns:
        print(f"\n{table_name}: {rsid_columns}")