# Modules update
## Notebook to update current just-dna-seq modules

In [19]:
import polars as pl
import polars_bio as pb
import sqlite3
from pathlib import Path
from pycomfort import files

from platformdirs import user_cache_dir

# Configure Polars to show more rows and columns
pl.Config.set_tbl_rows(-1)  # Show all rows
pl.Config.set_tbl_cols(-1)  # Show all columns
pl.Config.set_tbl_width_chars(1000)  # Increase table width
pl.Config.set_fmt_str_lengths(1000)  # Show longer string values without truncation

polars.config.Config

In [30]:
from os import listdir
from prepare_annotations.cli import dbsnp_t2t
from prepare_annotations.resource import get_cache_dir
cache = get_cache_dir()
ensembl_cache = cache / "ensembl" / "homo_sapiens" 
clinvar_cache = cache / "clinvar"
dbsnp_t2t_cache = cache / "db"
listdir(ensembl_cache)

/home/antonkulaga/sources/prepare-annotations/.venv/lib/python3.13/site-packages/prefect/context.py:990: UserWarning: Failed to create the Prefect home directory at data/interim/prefect
  GLOBAL_SETTINGS_CONTEXT: SettingsContext = root_settings_context()

['homo_sapiens-chr2.parquet',
 'homo_sapiens-chr9.parquet',
 'homo_sapiens-chr17.parquet',
 'homo_sapiens-chr21.parquet',
 'homo_sapiens-chr8.parquet',
 'homo_sapiens-chrY.parquet',
 'homo_sapiens-chr20.parquet',
 'homo_sapiens-chr19.parquet',
 'homo_sapiens-chr4.parquet',
 'homo_sapiens-chr14.parquet',
 'homo_sapiens-chr3.parquet',
 'homo_sapiens-chr13.parquet',
 'homo_sapiens-chrX.parquet',
 'homo_sapiens-chr6.parquet',
 'homo_sapiens-chr5.parquet',
 'homo_sapiens-chr22.parquet',
 'homo_sapiens-chr1.parquet',
 'homo_sapiens-chrMT.parquet',
 'vcf',
 'homo_sapiens-chr15.parquet',
 'homo_sapiens-chr16.parquet',
 'homo_sapiens-chr7.parquet',
 'homo_sapiens-chr12.parquet',
 'homo_sapiens-chr18.parquet',
 'homo_sapiens-chr11.parquet',
 'homo_sapiens-chr10.parquet']

In [31]:
from pycomfort.files import tprint
tprint(clinvar_cache)

clinvar
	clinvar_20260104_VEP.parquet
	vcf
		clinvar_20260104_VEP.vcf.gz
		.fsspec_cache

In [32]:
clinvar = pl.scan_parquet(clinvar_cache / "clinvar_20260104_VEP.parquet")
clinvar.head(5).collect()

shape: (5, 50)
┌───────┬───────┬───────┬─────────┬─────┬─────┬───────────┬──────┬────────┬────────┬─────────┬────────┬──────────┬──────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────┬──────────────┬─────────────────────────────┬────────────────────────────────────────────┬────────────────────────────┬────────────┬────────────┬──────────────────┬───────────────────────────┬────────────┬─────────────────────────┬───────────┬─────────────┬─────────────────────────────────┬───────────┬───────────┬───────────┬──────────────┬───────────┬───────────┬────────────┬───────────┬───────────┬───────────┬────────────────┬───────────┬───────────┬───────────┬──────────────┬────────────┬───────────┬───────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┐
│ chrom ┆ start ┆ end   ┆ id      ┆ ref ┆ alt ┆ alts      ┆ qual ┆ filter ┆ AF_ESP ┆ AF_EXAC ┆ AF_TGP ┆ ALLELEID ┆ CLNDN                    ┆ CLNDNINCL ┆ CLNDISDB                                                                         ┆ CLNDISDBINCL ┆ CLNHGVS                     ┆ CLNREVSTAT                                 ┆ CLNSIG                     ┆ CLNSIGCONF ┆ CLNSIGINCL ┆ CLNSIGSCV        ┆ CLNVC                     ┆ CLNVCSO    ┆ CLNVI                   ┆ DBVARID   ┆ GENEINFO    ┆ MC                              ┆ ONCDN     ┆ ONCDNINCL ┆ ONCDISDB  ┆ ONCDISDBINCL ┆ ONC       ┆ ONCINCL   ┆ ONCREVSTAT ┆ ONCSCV    ┆ ONCCONF   ┆ ORIGIN    ┆ RS             ┆ SCIDN     ┆ SCIDNINCL ┆ SCIDISDB  ┆ SCIDISDBINCL ┆ SCIREVSTAT ┆ SCI       ┆ SCIINCL   ┆ SCISCV    ┆ CSQ                                                                                                                                                                                                                    ┆ phlyoP100way │
│ ---   ┆ ---   ┆ ---   ┆ ---     ┆ --- ┆ --- ┆ ---       ┆ ---  ┆ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---      ┆ ---                      ┆ ---       ┆ ---                                                                              ┆ ---          ┆ ---                         ┆ ---                                        ┆ ---                        ┆ ---        ┆ ---        ┆ ---              ┆ ---                       ┆ ---        ┆ ---                     ┆ ---       ┆ ---         ┆ ---                             ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---       ┆ ---       ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---            ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---                                                                                                                                                                                                                    ┆ ---          │
│ str   ┆ u32   ┆ u32   ┆ str     ┆ str ┆ str ┆ list[str] ┆ f64  ┆ str    ┆ f32    ┆ f32     ┆ f32    ┆ i32      ┆ list[str]                ┆ list[str] ┆ list[str]                                                                        ┆ list[str]    ┆ list[str]                   ┆ list[str]                                  ┆ list[str]                  ┆ list[str]  ┆ list[str]  ┆ list[str]        ┆ str                       ┆ str        ┆ list[str]               ┆ list[str] ┆ str         ┆ list[str]                       ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str] ┆ list[str] ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]      ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]                                                                                                                                                                                                              ┆ list[str]    │
╞═══════╪═══════╪═══════╪═════════╪═════╪═════╪═══════════╪══════╪════════╪════════╪═════════╪════════╪══════════╪══════════════════════════╪═══════════╪══════════════════════════════════════════════════════════════════════════════════╪══════════════╪═════════════════════════════╪════════════════════════════════════════════╪════════════════════════════╪════════════╪════════════╪══════════════════╪═══════════════════════════╪════════════╪═════════════════════════╪═══════════╪═════════════╪═════════════════════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪═══════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════╡
│ 1     ┆ 66926 ┆ 66927 ┆ 3385321 ┆ AG  ┆ A   ┆ ["A"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3544463  ┆ ["Retinitis_pigmentosa"] ┆ null      ┆ ["Human_Phenotype_Ontology:HP:0000547", "MONDO:MONDO:0019200", … "Orphanet:791"] ┆ null         ┆ ["NC_000001.11:g.66927del"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV005419006"] ┆ Deletion                  ┆ SO:0000159 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001627|intron_variant"]   ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["0"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["-|downstream_gene_variant|MODIFIER|OR4G11P|ENSG00000240361|Transcript|ENST00000492842.2|transcribed_unprocessed_pseudogene|||||||||||3040|1||deletion|1:66926:G:|HGNC|HGNC:31276|||||||||||||||||||||||||||||||g|||| ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 0.143999993801117", "-|intron_variant|MODIFIER|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding||2/2|ENST00000641515.2:c.9+1354del|||||||||1||deletion|1:66926:G:|HGNC|HGNC:14825|ENSP00000493376|||| ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ ||||||||||||||||||||||||||g||||0.143999993801117", …                                                                                                                                                                   ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ "-|downstream_gene_variant|MODIFIER||ENSG00000290826|Transcript|ENST00000832531.1|lncRNA|||||||||||3401|1||deletion|1:66926:G:|||||||||||||||||||||||||||||||||g||||0.143999993801117"]                                ┆              │
│ 1     ┆ 69134 ┆ 69134 ┆ 2205837 ┆ A   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 2193183  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69134A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Likely_benign"]          ┆ null       ┆ null       ┆ ["SCV003526545"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA502008"]    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["781394307"]  ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.107A>G|ENSP00000493376.2:p.Glu36Gly|167|107|36|E/G|gAa/gGa|rs781394307||1||SNV|1:69133:A:G|HG ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ NC|HGNC:14825|ENSP00000493376||tolerated(0.08)|benign(0.007)||likely_benign||1||ClinVar::RCV002668554&VCV002205837&RCV004071174||||||16.64|1.975028||45|-1|-19|-1|0.00|0.00|0.02|0.00|OR4F5||||N||||0.405000001192093" ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ ]                                                                                                                                                                                                                      ┆              │
│ 1     ┆ 69308 ┆ 69308 ┆ 3925305 ┆ A   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039319  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69308A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120601"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.281A>G|ENSP00000493376.2:p.Lys94Arg|341|281|94|K/R|aAg/aGg|||1||SNV|1:69307:A:G|HGNC|HGNC:148 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 25|ENSP00000493376||deleterious(0.02)|benign(0.093)||||||||||||18.76|2.446142||-12|26|1|31|0.01|0.00|0.00|0.00|OR4F5||||a||||1.42999994754791"]                                                                        ┆              │
│ 1     ┆ 69314 ┆ 69314 ┆ 3205580 ┆ T   ┆ G   ┆ ["G"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3374047  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69314T>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV004995495"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA338197388"] ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["2521653848"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.287T>G|ENSP00000493376.2:p.Ile96Ser|347|287|96|I/S|aTt/aGt|||1||SNV|1:69313:T:G|HGNC|HGNC:148 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 25|ENSP00000493376||deleterious(0)|possibly_damaging(0.652)||||||||||||22.7|3.512588||-12|-18|-1|25|0.00|0.00|0.04|0.00|OR4F5||||t||||4.60900020599365"]                                                               ┆              │
│ 1     ┆ 69404 ┆ 69404 ┆ 3925306 ┆ T   ┆ C   ┆ ["C"]     ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039320  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69404T>C"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120602"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["C|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.377T>C|ENSP00000493376.2:p.Met126Thr|437|377|126|M/T|aTg/aCg|rs1328728149||1||SNV|1:69403:T:C ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆           ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ |HGNC|HGNC:14825|ENSP00000493376||deleterious(0)|benign(0.07)||||||||||||19.11|2.526974||-34|-49|1|-13|0.00|0.00|0.00|0.00|OR4F5||||t||||0.241999998688698"]                                                           ┆              │
└───────┴───────┴───────┴─────────┴─────┴─────┴───────────┴──────┴────────┴────────┴─────────┴────────┴──────────┴──────────────────────────┴───────────┴──────────────────────────────────────────────────────────────────────────────────┴──────────────┴─────────────────────────────┴────────────────────────────────────────────┴────────────────────────────┴────────────┴────────────┴──────────────────┴───────────────────────────┴────────────┴─────────────────────────┴───────────┴─────────────┴─────────────────────────────────┴───────────┴───────────┴───────────┴──────────────┴───────────┴───────────┴────────────┴───────────┴───────────┴───────────┴────────────────┴───────────┴───────────┴───────────┴──────────────┴────────────┴───────────┴───────────┴───────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┘

In [36]:
clinvar_vcf = pb.scan_vcf(str(clinvar_cache / "vcf" / "clinvar_20260104_VEP.vcf.gz"))
clinvar_vcf.head(10).collect()

10rows [00:00, 56.72rows/s]

shape: (10, 49)
┌───────┬───────┬───────┬─────────┬─────┬─────┬──────┬────────┬────────┬─────────┬────────┬──────────┬──────────────────────────┬───────────┬──────────────────────────────────────────────────────────────────────────────────┬──────────────┬─────────────────────────────┬────────────────────────────────────────────┬────────────────────────────┬────────────┬────────────┬──────────────────┬───────────────────────────┬────────────┬─────────────────────────┬───────────┬─────────────┬─────────────────────────────────┬───────────┬───────────┬───────────┬──────────────┬───────────┬───────────┬────────────┬───────────┬───────────┬───────────┬────────────────┬───────────┬───────────┬───────────┬──────────────┬────────────┬───────────┬───────────┬───────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┐
│ chrom ┆ start ┆ end   ┆ id      ┆ ref ┆ alt ┆ qual ┆ filter ┆ AF_ESP ┆ AF_EXAC ┆ AF_TGP ┆ ALLELEID ┆ CLNDN                    ┆ CLNDNINCL ┆ CLNDISDB                                                                         ┆ CLNDISDBINCL ┆ CLNHGVS                     ┆ CLNREVSTAT                                 ┆ CLNSIG                     ┆ CLNSIGCONF ┆ CLNSIGINCL ┆ CLNSIGSCV        ┆ CLNVC                     ┆ CLNVCSO    ┆ CLNVI                   ┆ DBVARID   ┆ GENEINFO    ┆ MC                              ┆ ONCDN     ┆ ONCDNINCL ┆ ONCDISDB  ┆ ONCDISDBINCL ┆ ONC       ┆ ONCINCL   ┆ ONCREVSTAT ┆ ONCSCV    ┆ ONCCONF   ┆ ORIGIN    ┆ RS             ┆ SCIDN     ┆ SCIDNINCL ┆ SCIDISDB  ┆ SCIDISDBINCL ┆ SCIREVSTAT ┆ SCI       ┆ SCIINCL   ┆ SCISCV    ┆ CSQ                                                                                                                                                                                                                                ┆ phlyoP100way │
│ ---   ┆ ---   ┆ ---   ┆ ---     ┆ --- ┆ --- ┆ ---  ┆ ---    ┆ ---    ┆ ---     ┆ ---    ┆ ---      ┆ ---                      ┆ ---       ┆ ---                                                                              ┆ ---          ┆ ---                         ┆ ---                                        ┆ ---                        ┆ ---        ┆ ---        ┆ ---              ┆ ---                       ┆ ---        ┆ ---                     ┆ ---       ┆ ---         ┆ ---                             ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---       ┆ ---       ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---            ┆ ---       ┆ ---       ┆ ---       ┆ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---                                                                                                                                                                                                                                ┆ ---          │
│ str   ┆ u32   ┆ u32   ┆ str     ┆ str ┆ str ┆ f64  ┆ str    ┆ f32    ┆ f32     ┆ f32    ┆ i32      ┆ list[str]                ┆ list[str] ┆ list[str]                                                                        ┆ list[str]    ┆ list[str]                   ┆ list[str]                                  ┆ list[str]                  ┆ list[str]  ┆ list[str]  ┆ list[str]        ┆ str                       ┆ str        ┆ list[str]               ┆ list[str] ┆ str         ┆ list[str]                       ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str] ┆ list[str] ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]      ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]    ┆ list[str]  ┆ list[str] ┆ list[str] ┆ list[str] ┆ list[str]                                                                                                                                                                                                                          ┆ list[str]    │
╞═══════╪═══════╪═══════╪═════════╪═════╪═════╪══════╪════════╪════════╪═════════╪════════╪══════════╪══════════════════════════╪═══════════╪══════════════════════════════════════════════════════════════════════════════════╪══════════════╪═════════════════════════════╪════════════════════════════════════════════╪════════════════════════════╪════════════╪════════════╪══════════════════╪═══════════════════════════╪════════════╪═════════════════════════╪═══════════╪═════════════╪═════════════════════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪═══════════╪═══════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════╪═══════════╪═══════════╪═══════════╪══════════════╪════════════╪═══════════╪═══════════╪═══════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════╡
│ 1     ┆ 66926 ┆ 66927 ┆ 3385321 ┆ AG  ┆ A   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3544463  ┆ ["Retinitis_pigmentosa"] ┆ null      ┆ ["Human_Phenotype_Ontology:HP:0000547", "MONDO:MONDO:0019200", … "Orphanet:791"] ┆ null         ┆ ["NC_000001.11:g.66927del"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV005419006"] ┆ Deletion                  ┆ SO:0000159 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001627|intron_variant"]   ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["0"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["-|downstream_gene_variant|MODIFIER|OR4G11P|ENSG00000240361|Transcript|ENST00000492842.2|transcribed_unprocessed_pseudogene|||||||||||3040|1||deletion|1:66926:G:|HGNC|HGNC:31276|||||||||||||||||||||||||||||||g||||0.1439999938 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 01117", "-|intron_variant|MODIFIER|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding||2/2|ENST00000641515.2:c.9+1354del|||||||||1||deletion|1:66926:G:|HGNC|HGNC:14825|ENSP00000493376|||||||||||||||||||||||||||| ┆              │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ ||g||||0.143999993801117", … "-|downstream_gene_variant|MODIFIER||ENSG00000290826|Transcript|ENST00000832531.1|lncRNA|||||||||||3401|1||deletion|1:66926:G:|||||||||||||||||||||||||||||||||g||||0.143999993801117"]               ┆              │
│ 1     ┆ 69134 ┆ 69134 ┆ 2205837 ┆ A   ┆ G   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 2193183  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69134A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Likely_benign"]          ┆ null       ┆ null       ┆ ["SCV003526545"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA502008"]    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["781394307"]  ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.107A>G|ENSP00000493376.2:p.Glu36Gly|167|107|36|E/G|gAa/gGa|rs781394307||1||SNV|1:69133:A:G|HGNC|HGNC:1482 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 5|ENSP00000493376||tolerated(0.08)|benign(0.007)||likely_benign||1||ClinVar::RCV002668554&VCV002205837&RCV004071174||||||16.64|1.975028||45|-1|-19|-1|0.00|0.00|0.02|0.00|OR4F5||||N||||0.405000001192093"]                        ┆              │
│ 1     ┆ 69308 ┆ 69308 ┆ 3925305 ┆ A   ┆ G   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039319  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69308A>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120601"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.281A>G|ENSP00000493376.2:p.Lys94Arg|341|281|94|K/R|aAg/aGg|||1||SNV|1:69307:A:G|HGNC|HGNC:14825|ENSP00000 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 493376||deleterious(0.02)|benign(0.093)||||||||||||18.76|2.446142||-12|26|1|31|0.01|0.00|0.00|0.00|OR4F5||||a||||1.42999994754791"]                                                                                                ┆              │
│ 1     ┆ 69314 ┆ 69314 ┆ 3205580 ┆ T   ┆ G   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3374047  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69314T>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV004995495"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA338197388"] ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["2521653848"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.287T>G|ENSP00000493376.2:p.Ile96Ser|347|287|96|I/S|aTt/aGt|||1||SNV|1:69313:T:G|HGNC|HGNC:14825|ENSP00000 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 493376||deleterious(0)|possibly_damaging(0.652)||||||||||||22.7|3.512588||-12|-18|-1|25|0.00|0.00|0.04|0.00|OR4F5||||t||||4.60900020599365"]                                                                                       ┆              │
│ 1     ┆ 69404 ┆ 69404 ┆ 3925306 ┆ T   ┆ C   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4039320  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69404T>C"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006120602"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["C|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.377T>C|ENSP00000493376.2:p.Met126Thr|437|377|126|M/T|aTg/aCg|rs1328728149||1||SNV|1:69403:T:C|HGNC|HGNC:1 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 4825|ENSP00000493376||deleterious(0)|benign(0.07)||||||||||||19.11|2.526974||-34|-49|1|-13|0.00|0.00|0.00|0.00|OR4F5||||t||||0.241999998688698"]                                                                                   ┆              │
│ 1     ┆ 69423 ┆ 69423 ┆ 3205581 ┆ G   ┆ A   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 3374048  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69423G>A"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV004995496"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ ["ClinGen:CA338197763"] ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ ["2521654033"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["A|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.396G>A|ENSP00000493376.2:p.Met132Ile|456|396|132|M/I|atG/atA|||1||SNV|1:69422:G:A|HGNC|HGNC:14825|ENSP000 ┆ null         │
│       ┆       ┆       ┆         ┆     ┆     ┆      ┆        ┆        ┆         ┆        ┆          ┆                          ┆           ┆                                                                                  ┆              ┆                             ┆                                            ┆                            ┆            ┆            ┆                  ┆                           ┆            ┆                         ┆           ┆             ┆                                 ┆           ┆           ┆           ┆              ┆           ┆           ┆            ┆           ┆           ┆           ┆                ┆           ┆           ┆           ┆              ┆            ┆           ┆           ┆           ┆ 00493376||deleterious(0)|possibly_damaging(0.602)||||||||||||24.3|4.092007||2|12|-32|-30|0.00|0.00|0.01|0.00|OR4F5||||g||||7.42399978637695"]                                                                                      ┆              │
│ 1     ┆ 69506 ┆ 69506 ┆ 4127217 ┆ C   ┆ G   ┆ null ┆        ┆ null   ┆ null    ┆ null   ┆ 4241534  ┆ ["not_specified"]        ┆ null      ┆ ["MedGen:CN169374"]                                                              ┆ null         ┆ ["NC_000001.11:g.69506C>G"] ┆ ["criteria_provided", "_single_submitter"] ┆ ["Uncertain_significance"] ┆ null       ┆ null       ┆ ["SCV006383905"] ┆ single_nucleotide_variant ┆ SO:0001483 ┆ null                    ┆ null      ┆ OR4F5:79501 ┆ ["SO:0001583|missense_variant"] ┆ null      ┆ null      ┆ null      ┆ null         ┆ null      ┆ null      ┆ null       ┆ null      ┆ null      ┆ ["1"]     ┆ null           ┆ null      ┆ null      ┆ null      ┆ null         ┆ null       ┆ null      ┆ null      ┆ null      ┆ ["G|missense_variant|MODERATE|OR4F5|ENSG00000186092|Transcript|ENST00000641515.2|protein_coding|3/3||ENST00000641515.2:c.479C>G|ENSP00000493376.2:p.Ala160Gly|539|479|160|A/G|gCt/gGt|||1||SNV|1:69505:C:G|HGNC|HGNC:14825|ENSP000 ┆ null         │

### Testing the parquets

In [37]:
chr1 = pl.scan_parquet(ensembl_cache / "homo_sapiens-chr1.parquet")
chr1.head(5).collect()

shape: (5, 41)
┌───────┬───────┬───────┬──────────────┬─────┬───────┬─────────────────┬──────┬────────┬────────────┬────────────────┬───────────┬───────────────────┬─────┬─────────┬─────────────────────────┬────────┬──────────┬──────────┬────────────────────────┬───────┬──────────┬─────────┬────────┬──────────────────┬─────────────────┬──────────────────────────┬────────────┬────────────────────┬─────────────────────────────┬─────────────┬────────────────────────┬─────────────────┬────────────────────┬─────────────────────────┬───────────────────┬──────────────────┬──────┬──────┬──────┬──────┐
│ chrom ┆ start ┆ end   ┆ id           ┆ ref ┆ alt   ┆ alts            ┆ qual ┆ filter ┆ COSMIC_101 ┆ ClinVar_202502 ┆ dbSNP_156 ┆ HGMD-PUBLIC_20204 ┆ TSA ┆ E_Cited ┆ E_Multiple_observations ┆ E_Freq ┆ E_TOPMed ┆ E_Hapmap ┆ E_Phenotype_or_Disease ┆ E_ESP ┆ E_gnomAD ┆ E_1000G ┆ E_ExAC ┆ CLIN_risk_factor ┆ CLIN_protective ┆ CLIN_confers_sensitivity ┆ CLIN_other ┆ CLIN_drug_response ┆ CLIN_uncertain_significance ┆ CLIN_benign ┆ CLIN_likely_pathogenic ┆ CLIN_pathogenic ┆ CLIN_likely_benign ┆ CLIN_histocompatibility ┆ CLIN_not_provided ┆ CLIN_association ┆ MA   ┆ MAF  ┆ MAC  ┆ AA   │
│ ---   ┆ ---   ┆ ---   ┆ ---          ┆ --- ┆ ---   ┆ ---             ┆ ---  ┆ ---    ┆ ---        ┆ ---            ┆ ---       ┆ ---               ┆ --- ┆ ---     ┆ ---                     ┆ ---    ┆ ---      ┆ ---      ┆ ---                    ┆ ---   ┆ ---      ┆ ---     ┆ ---    ┆ ---              ┆ ---             ┆ ---                      ┆ ---        ┆ ---                ┆ ---                         ┆ ---         ┆ ---                    ┆ ---             ┆ ---                ┆ ---                     ┆ ---               ┆ ---              ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ str   ┆ u32   ┆ u32   ┆ str          ┆ str ┆ str   ┆ list[str]       ┆ f64  ┆ str    ┆ bool       ┆ bool           ┆ bool      ┆ bool              ┆ str ┆ bool    ┆ bool                    ┆ bool   ┆ bool     ┆ bool     ┆ bool                   ┆ bool  ┆ bool     ┆ bool    ┆ bool   ┆ bool             ┆ bool            ┆ bool                     ┆ bool       ┆ bool               ┆ bool                        ┆ bool        ┆ bool                   ┆ bool            ┆ bool               ┆ bool                    ┆ bool              ┆ bool             ┆ str  ┆ f32  ┆ i32  ┆ str  │
╞═══════╪═══════╪═══════╪══════════════╪═════╪═══════╪═════════════════╪══════╪════════╪════════════╪════════════════╪═══════════╪═══════════════════╪═════╪═════════╪═════════════════════════╪════════╪══════════╪══════════╪════════════════════════╪═══════╪══════════╪═════════╪════════╪══════════════════╪═════════════════╪══════════════════════════╪════════════╪════════════════════╪═════════════════════════════╪═════════════╪════════════════════════╪═════════════════╪════════════════════╪═════════════════════════╪═══════════════════╪══════════════════╪══════╪══════╪══════╪══════╡
│ 1     ┆ 10001 ┆ 10001 ┆ rs1570391677 ┆ T   ┆ A|C   ┆ ["A", "C"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10002 ┆ 10002 ┆ rs1570391692 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10003 ┆ 10003 ┆ rs1570391694 ┆ A   ┆ C     ┆ ["C"]           ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10007 ┆ 10007 ┆ rs1639538116 ┆ T   ┆ C|G   ┆ ["C", "G"]      ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
│ 1     ┆ 10008 ┆ 10008 ┆ rs1570391698 ┆ A   ┆ C|G|T ┆ ["C", "G", "T"] ┆ null ┆        ┆ false      ┆ false          ┆ true      ┆ false             ┆ SNV ┆ false   ┆ false                   ┆ true   ┆ false    ┆ false    ┆ false                  ┆ false ┆ false    ┆ false   ┆ false  ┆ false            ┆ false           ┆ false                    ┆ false      ┆ false              ┆ false                       ┆ false       ┆ false                  ┆ false           ┆ false              ┆ false                   ┆ false             ┆ false            ┆ null ┆ null ┆ null ┆ null │
└───────┴───────┴───────┴──────────────┴─────┴───────┴─────────────────┴──────┴────────┴────────────┴────────────────┴───────────┴───────────────────┴─────┴─────────┴─────────────────────────┴────────┴──────────┴──────────┴────────────────────────┴───────┴──────────┴─────────┴────────┴──────────────────┴─────────────────┴──────────────────────────┴────────────┴────────────────────┴─────────────────────────────┴─────────────┴────────────────────────┴─────────────────┴────────────────────┴─────────────────────────┴───────────────────┴──────────────────┴──────┴──────┴──────┴──────┘

In [ ]:
from pycomfort.files import tprint
clinvar_cache = cache / "clinvar"
tprint(cache, depth=1)

just-dna-pipelines
	dbsnp_grch38
		vcf
			GCF_000001405.40.gz
			.fsspec_cache
	clinvar
		clinvar_20260104_VEP.parquet
		vcf
			clinvar_20260104_VEP.vcf.gz
			.fsspec_cache
	dbsnp_t2t
		chm13v2.0_dbSNPv155.vcf.tmp.parquet
		chm13v2.0_dbSNPv155.vcf.parquet
		chm13v2.0_dbSNPv155.vcf.gz
		chm13v2.0_dbSNPv155.vcf.gz.tbi
		vcf
			chm13v2.0_dbSNPv155.vcf.gz
			chm13v2.0_dbSNPv155.vcf.gz.tbi
			.fsspec_cache
		parquet
			chm13v2.0_dbSNPv155.vcf.tmp.parquet
	.fsspec_cache
		20f9321d22b6bf386b0a23d2499243e195aff8e21d1654a53c0da8019c8a8b7a
		0416f6134bd5c84286ebd4fffe845a4d6768e6f86f069a0773eff784aa4c084d
		765b8fa0647d27df66fbfa8c859f77d0c565bbb9e7ab15760b7e0e0e84a59638
		dca203f561595c9b659bd8b85a57c4b23e1ff6d02bced4cdc786b77fd31c299c
		2e23a05fd1d65acd59d1d9342e201e0f96aef41d030ba274858a733a3b89af45
		955092064d2abb285773b06afeba9f4c5433ef6c7e44d484c8a2d8ec76f5a89c
		8b12c9270181eff64730438982c27e1abf94bc8cc306d81afecba3bcdb3f2756
		b29bc733eeeefd2f16b04d3b2b388f708d012d2da8b2e8548843c1a7fe09e6dd
		3e6b27d87ef73d02741a7a31dfadc5500c625cf849e15b27fb2eddf0e593a4d7
		a98b26f48b8ae5cff08d83198727e25ddf71e9f74999d8b7cc68ae23fad793d1
		b6f04df9d2463af48af3ed7a076f31c747bfb76d926eea0e99f8e5fb99aee2de
		c1532e95aff03762d0f1d262033880a9a0ee5dbf0ab5fbbeab59739f82bebc06
		a1e660f1b6f8881723856fb15da4edc90431fc4da7788f10ace8a998b8c4f1df
		5fc199031ab98e57f415aa9bcb5740eb7334ed7365a0da72e44ff8b124fc7449
		685a2f8f3e41bc3782d359c16431508be8430f9d9ecef023ac1df2ba34e5f9d7
		a70e19f5693abcbf0b72ea5af221c8a038655e4807b7b6810ad37a4764318df2
		5b966915ba0e3827996869f03b4618e6f278af900af91d8d70afcc571e725dcc
		26dfe358b5f64aea425b5338ae317d484e32f262a08112709364e693faacfff1
		c57b22848598d8852c32b677bc5e7a0f2e38f96b80ec6d21b53b14302f7d2bb7
		0c30a73e6f464f62a5ff04eaa5c4899b1bded084163bab70d7b28c538d478335
		1dd5263e68ef09c17aecad303b7d8b8c924590ad8fb0ed8a4eb0c40e9bad9ca8
		2491340ace46c4a9b3ab6b3d2b9a3132612aa4b5a226f527b2c5305ec4b103f5
		bdc6dfcff61193ed6c868d0c1c9f65df8668827d81fe16f335b0fdd4ef600a45
		97cf0fab0d97a98f4eec6c34a3b769ef5de682c5d20ab1654a01b8b0351f622b
		321ea42b5fb07231dd7c3c7ff22766ce79b484289982106002b426781268501b
		cache
		0833c226e7ce27f2dcfdf5fe14e82f0d4822548f10084d932a5174429ab32ebc
	ensembl
		homo_sapiens
			homo_sapiens-chr2.parquet
			homo_sapiens-chr9.parquet
			homo_sapiens-chr17.parquet
			homo_sapiens-chr21.parquet
			homo_sapiens-chr8.parquet
			homo_sapiens-chrY.parquet
			homo_sapiens-chr20.parquet
			homo_sapiens-chr19.parquet
			homo_sapiens-chr4.parquet
			homo_sapiens-chr14.parquet
			homo_sapiens-chr3.parquet
			homo_sapiens-chr13.parquet
			homo_sapiens-chrX.parquet
			homo_sapiens-chr6.parquet
			homo_sapiens-chr5.parquet
			homo_sapiens-chr22.parquet
			homo_sapiens-chr1.parquet
			homo_sapiens-chrMT.parquet
			homo_sapiens-chr15.parquet
			homo_sapiens-chr16.parquet
			homo_sapiens-chr7.parquet
			homo_sapiens-chr12.parquet
			homo_sapiens-chr18.parquet
			homo_sapiens-chr11.parquet
			homo_sapiens-chr10.parquet
			vcf
				homo_sapiens-chr1.vcf.gz
				homo_sapiens-chr5.vcf.gz
				homo_sapiens-chr6.vcf.gz
				homo_sapiens-chr9.vcf.gz
				homo_sapiens-chr10.vcf.gz
				homo_sapiens-chr21.vcf.gz
				homo_sapiens-chr4.vcf.gz
				homo_sapiens-chr17.vcf.gz
				homo_sapiens-chr14.vcf.gz
				homo_sapiens-chr2.vcf.gz
				homo_sapiens-chr19.vcf.gz
				homo_sapiens-chr22.vcf.gz
				homo_sapiens-chr8.vcf.gz
				homo_sapiens-chr20.vcf.gz
				homo_sapiens-chr16.vcf.gz
				homo_sapiens-chrX.vcf.gz
				homo_sapiens-chr7.vcf.gz
				homo_sapiens-chrY.vcf.gz
				homo_sapiens-chr15.vcf.gz
				homo_sapiens-chr11.vcf.gz
				homo_sapiens-chrMT.vcf.gz
				homo_sapiens-chr18.vcf.gz
				homo_sapiens-chr13.vcf.gz
				homo_sapiens-chr12.vcf.gz
				homo_sapiens-chr3.vcf.gz
				.fsspec_cache
	gnomad_v4
	repositories
		dna-seq_just_cancer
			README.md
			just_cancer.py
			just_cancer.yml
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.pack
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.idx
						pack-0500909bf2d473f1720465cda319c303f3c0f48e.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				genes.txt
		dna-seq_just_longevitymap
			README.md
			just_longevitymap.yml
			LICENSE
			just_longevitymap.py
			.gitignore
			longevitymap_ref_homo.py
			logo.png
			.git
				index
				packed-refs
				config
				ORIG_HEAD
				HEAD
				FETCH_HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.idx
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.pack
						pack-8ade12ffac84cf98a244612e7889206a5bde498d.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				longevitymap.sqlite
		dna-seq_just_drugs
			README.md
			LICENSE
			.gitignore
			just_drugs.yml
			just_drugs.py
			logo.png
			.git
				index
				packed-refs
				config
				ORIG_HEAD
				HEAD
				FETCH_HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.idx
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.rev
						pack-22d4d4512046f548c9bb9482cbe937e18257a66e.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				annotation_tab.tsv
		dna-seq_just_lipidmetabolism
			README.md
			lipidmetabolism_ref_homo.py
			just_lipidmetabolism.yml
			just_lipidmetabolism.py
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.rev
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.idx
						pack-fc3989f1a95cdd18d5fa44255b1d967185a2a9b7.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				lipid_metabolism.sqlite
		dna-seq_just_coronary
			README.md
			coronary_ref_homo.py
			just_coronary.yml
			LICENSE
			.gitignore
			logo.png
			just_coronary.py
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.idx
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.pack
						pack-a83fac7f4c96743f73daade4847f683a1e0aa1a5.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				coronary.sqlite
		dna-seq_just_prs
			README.md
			just_prs.py
			just_prs.yml
			LICENSE
			.gitignore
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							master
				objects
					info
					pack
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.idx
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.rev
						pack-5edb96eb70549b0ea2fde09a8363cf4cea4d7016.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						master
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				prs.sqlite
		dna-seq_just_superhuman
			README.md
			superhumansite.png
			just_superhuman.yml
			just_superhuman.py
			LICENSE
			.gitignore
			just_superhuman.md
			logo.png
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.idx
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.rev
						pack-5a6b414fd07afc048c55da0c3e2c7f332ee4e3db.pack
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				superhuman.sqlite
			example
				antonkulaga.vcf.superhuman.html
		dna-seq_just_vo2max
			README.md
			vo2max_ref_homo.py
			just_vo2max.py
			LICENSE
			just_vo2max.yml
			.gitignore
			.git
				index
				packed-refs
				config
				HEAD
				description
				branches
				logs
					HEAD
					refs
						remotes
							origin
								HEAD
						heads
							main
				objects
					info
					pack
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.idx
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.pack
						pack-65f24937b7965fde615c13a6e17ce49231a1579a.rev
				info
					exclude
				refs
					tags
					remotes
						origin
							HEAD
					heads
						main
				hooks
					pre-commit.sample
					pre-applypatch.sample
					post-update.sample
					pre-rebase.sample
					applypatch-msg.sample
					prepare-commit-msg.sample
					push-to-checkout.sample
					pre-merge-commit.sample
					pre-push.sample
					update.sample
					commit-msg.sample
					sendemail-validate.sample
					fsmonitor-watchman.sample
					pre-receive.sample
			data
				vo2max.sqlite

## Loading modules

In [12]:
from pycomfort import files
from pathlib import Path
base = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
data = base / "data"
modules = data / "modules"
files.tprint(modules)

modules
	just_drugs
		annotation_tab.tsv
	just_longevitymap
		longevitymap.sqlite
	just_coronary
		coronary.sqlite
	just_lipidmetabolism
		lipid_metabolism.sqlite
	just_vo2max
		vo2max.sqlite
	just_superhuman
		superhuman.sqlite
	just_prs
		prs.sqlite
	just_cancer
		genes.txt

## Modules

In [38]:
import sqlite3
import polars as pl

# Connect to the database
db_path = modules / "just_longevitymap" / "longevitymap.sqlite"
conn = sqlite3.connect(db_path)

# Get list of all tables in the database
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables in the database:")
for table in tables:
    print(f"  - {table[0]}")

Tables in the database:
  - gene
  - population
  - variant
  - allele_weights
  - categories

In [39]:
# Get schema for each table
for table in tables:
    table_name = table[0]
    print(f"\nSchema for table '{table_name}':")
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    for col in columns:
        print(f"  {col[1]} ({col[2]})")

Schema for table 'gene':
  id (INTEGER)
  name (TEXT)
  symbol (TEXT)
  alias (TEXT)
  description (TEXT)
  omim (TEXT)
  ensembl (TEXT)
  uniprot (TEXT)
  unigene (TEXT)
  cytogenetic_location (TEXT)

Schema for table 'population':
  id (INTEGER)
  name (TEXT)

Schema for table 'variant':
  id (INTEGER)
  location (TEXT)
  study_design (TEXT)
  conclusions (TEXT)
  association (TEXT)
  gender (TEXT)
  quickref (TEXT)
  quickyear (INTEGER)
  quickpubmed (TEXT)
  identifier (TEXT)
  gene_id (INTEGER)
  population_id (INTEGER)

Schema for table 'allele_weights':
  id (INTEGER)
  allele (TEXT)
  state (TEXT)
  zygosity (TEXT)
  weight (REAL)
  rsid (TEXT)
  priority (TEXT)
  category_id (INTEGER)

Schema for table 'categories':
  id (INTEGER)
  name (TEXT)

## Join with rsid

In [7]:
weights = pl.read_database("SELECT id, allele, state, zygosity, weight, rsid, priority, category_id FROM allele_weights", connection=conn)
weights.head(5)

shape: (5, 8)
┌─────┬────────┬───────┬──────────┬────────┬──────────┬──────────┬─────────────┐
│ id  ┆ allele ┆ state ┆ zygosity ┆ weight ┆ rsid     ┆ priority ┆ category_id │
│ --- ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---      ┆ ---      ┆ ---         │
│ i64 ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str      ┆ str      ┆ i64         │
╞═════╪════════╪═══════╪══════════╪════════╪══════════╪══════════╪═════════════╡
│ 0   ┆ T      ┆ alt   ┆ het      ┆ 0.5    ┆ rs7412   ┆ 1.0      ┆ 1           │
│ 1   ┆ T      ┆ alt   ┆ hom      ┆ 1.0    ┆ rs7412   ┆ 1.0      ┆ 1           │
│ 2   ┆ C      ┆ alt   ┆ het      ┆ -0.5   ┆ rs429358 ┆ 1.0      ┆ 1           │
│ 3   ┆ C      ┆ alt   ┆ hom      ┆ -1.0   ┆ rs429358 ┆ 1.0      ┆ 1           │
│ 4   ┆ G      ┆ ref   ┆ hom      ┆ 0.97   ┆ rs5882   ┆ 0.97     ┆ 1           │
└─────┴────────┴───────┴──────────┴────────┴──────────┴──────────┴─────────────┘

In [8]:
# Get unique rsids from small weights table
rsids = weights["rsid"].unique().to_list()
print(f"Filtering for {len(rsids)} unique rsids")

Filtering for 528 unique rsids

In [9]:
# Filter the large lazy frame first, then join
joined = df_ensembl.select(
    pl.col("chrom"), 
    pl.col("start"), 
    pl.col("end")
    ).filter(
    pl.col("id").is_in(rsids)
).join(
    weights.lazy(),
    left_on="id",
    right_on="rsid",
    how="inner"
)

In [10]:
example = joined.head(5).collect(engine="streaming")
example

ColumnNotFoundError: unable to find column "id"; valid columns: ["chrom", "start", "end"]

Resolved plan until failure:

	---> FAILED HERE RESOLVING 'sink' <---
SELECT [col("chrom"), col("start"), col("end")]
  Parquet SCAN [/home/antonkulaga/.cache/just_dna_pipelines/ensembl_variations/splitted_variants/SNV/homo_sapiens-chr1.parquet, ... 24 other sources] [id: 129231707533808]
  PROJECT */40 COLUMNS

In [26]:
result = joined.collect(engine="streaming")
result

shape: (1_788, 47)
┌───────┬──────────┬──────────┬────────────┬───┬──────────┬────────┬──────────┬─────────────┐
│ chrom ┆ start    ┆ end      ┆ id         ┆ … ┆ zygosity ┆ weight ┆ priority ┆ category_id │
│ ---   ┆ ---      ┆ ---      ┆ ---        ┆   ┆ ---      ┆ ---    ┆ ---      ┆ ---         │
│ str   ┆ u32      ┆ u32      ┆ str        ┆   ┆ str      ┆ f64    ┆ str      ┆ i64         │
╞═══════╪══════════╪══════════╪════════════╪═══╪══════════╪════════╪══════════╪═════════════╡
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005  ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 19    ┆ 44919689 ┆ 44919689 ┆ rs4420638  ┆ … ┆ het      ┆ -0.375 ┆ 0.75     ┆ 1           │
│ …     ┆ …        ┆ …        ┆ …          ┆ … ┆ …        ┆ …      ┆ …        ┆ …           │
│ 12    ┆ 57774005 ┆ 57774005 ┆ rs10877015 ┆ … ┆ hom      ┆ 0.12   ┆ 0.12     ┆ 11          │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ het      ┆ 0.065  ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ het      ┆ 0.065  ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ hom      ┆ 0.13   ┆ 0.13     ┆ 0           │
│ 22    ┆ 44203572 ┆ 44203572 ┆ rs139170   ┆ … ┆ hom      ┆ 0.13   ┆ 0.13     ┆ 0           │
└───────┴──────────┴──────────┴────────────┴───┴──────────┴────────┴──────────┴─────────────┘

In [33]:
weights.filter(pl.col("rsid") == "rs7896005")

shape: (2, 8)
┌─────┬────────┬───────┬──────────┬────────┬───────────┬──────────┬─────────────┐
│ id  ┆ allele ┆ state ┆ zygosity ┆ weight ┆ rsid      ┆ priority ┆ category_id │
│ --- ┆ ---    ┆ ---   ┆ ---      ┆ ---    ┆ ---       ┆ ---      ┆ ---         │
│ i64 ┆ str    ┆ str   ┆ str      ┆ f64    ┆ str       ┆ str      ┆ i64         │
╞═════╪════════╪═══════╪══════════╪════════╪═══════════╪══════════╪═════════════╡
│ 39  ┆ G      ┆ alt   ┆ het      ┆ 0.36   ┆ rs7896005 ┆ 0.72     ┆ 5           │
│ 40  ┆ G      ┆ alt   ┆ hom      ┆ 0.72   ┆ rs7896005 ┆ 0.72     ┆ 5           │
└─────┴────────┴───────┴──────────┴────────┴───────────┴──────────┴─────────────┘

In [31]:
result.filter(pl.col("id") == "rs7896005")

shape: (4, 47)
┌───────┬──────────┬──────────┬───────────┬───┬──────────┬────────┬──────────┬─────────────┐
│ chrom ┆ start    ┆ end      ┆ id        ┆ … ┆ zygosity ┆ weight ┆ priority ┆ category_id │
│ ---   ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---    ┆ ---      ┆ ---         │
│ str   ┆ u32      ┆ u32      ┆ str       ┆   ┆ str      ┆ f64    ┆ str      ┆ i64         │
╞═══════╪══════════╪══════════╪═══════════╪═══╪══════════╪════════╪══════════╪═════════════╡
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ het      ┆ 0.36   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
│ 10    ┆ 67891367 ┆ 67891367 ┆ rs7896005 ┆ … ┆ hom      ┆ 0.72   ┆ 0.72     ┆ 5           │
└───────┴──────────┴──────────┴───────────┴───┴──────────┴────────┴──────────┴─────────────┘

In [15]:
weights.shape

(1043, 8)

In [ ]:
# Check all tables for columns containing 'rsid' or 'rs' in the name
for table in tables:
    table_name = table[0]
    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = cursor.fetchall()
    rsid_columns = [col[1] for col in columns if 'rs' in col[1].lower() or 'id' in col[1].lower()]
    if rsid_columns:
        print(f"\n{table_name}: {rsid_columns}")